# version: '3.9'
# services:
#   backend:
#     build: ./backend
#     ports:
#       - "8000:8000"
#     volumes:
#       - ./backend:/app
#     depends_on:
#       - redis
#   redis:
#     image: redis:latest
#     ports:
#       - "6379:6379"
version: '3.9'
services:
  backend:
    build: ../backend
    ports:
      - "8000:8000"
    volumes:
      - ../backend:/app
    depends_on:
      - redis
  redis:
    image: redis:latest
    ports:
      - "6379:6379"